server {
    listen       80;
    server_name  _;

    # 服务前端静态文件
    location / {
        root   /usr/share/nginx/html; # 前端文件根目录
        index  index.html index.htm; # 默认首页
        try_files $uri $uri/ /index.html; # 支持前端路由
    }

    # # HTML文件不缓存
    # location ~* \.(html)$ {
    #     root   /usr/share/nginx/html;
    #     add_header Cache-Control "no-cache, no-store, must-revalidate";
    #     add_header Pragma "no-cache";
    #     add_header Expires "0";
    # }

    # # 静态资源缓存一年（文件名包含hash，更新时会改变）
    # location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
    #     root   /usr/share/nginx/html;
    #     expires 1y;
    #     add_header Cache-Control "public, immutable";
    #     add_header X-Content-Type-Options "nosniff";
    # }

    # # 其他静态文件缓存一个月
    # location ~* \.(json|txt|xml)$ {
    #     root   /usr/share/nginx/html;
    #     expires 30d;
    #     add_header Cache-Control "public";
    # }

    # # 反向代理 /api/ 路径到 FastAPI 后端服务
    # location /api/ {
    #     proxy_pass http://192.168.1.85:8088;    
    #     proxy_http_version 1.1;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;
    #     proxy_read_timeout 90;
    # }



    # 日志
    access_log  /var/log/nginx/mag_access.log;
    error_log   /var/log/nginx/mag_error.log;
}

